### ISSUE TITLE
The exported zip file is broken

### ISSUE THREAD

**Issue by erbanku** [hyoban/kirika#1]
I can download the resource images from object storage now (I guessed it according to the file size), but unable to extract the exported zip file, occur an error when extracting the file. In consequence, they were unable to complete the extraction.
I tried with Bandizip and PeaZip, but all failed to extract the zip file.

- PeaZip

![image](https://user-images.githubusercontent.com/79493862/236727500-61a45650-aff6-4279-bd1b-7393bf002d56.png)
- Bandizip
 
![image](https://user-images.githubusercontent.com/79493862/236727579-1ffe2684-3dac-44ee-964b-d1036c3eeee3.png)

**Comment by hyoban** [comment]
Unable to reproduce, can you share a test openapi to my email (privacy related notes removed)

**Comment by erbanku** [comment]
It seems the problem is related to the file indicated in the above image (F7EDDBD7-43F1-445D-AD15-C5E342DED623.png), which is really large (dimension: 9218x23734 size: 6.1MB), after deleting the related memo and image the problem has been solved. thx btw.

<details>
<summary>Image Property Details</summary>

![image](https://user-images.githubusercontent.com/79493862/236732895-10f2fd31-5874-47dd-92bd-0e7b899c6d00.png)

</details>

**Comment by hyoban** [comment]
Might be related to https://vercel.com/docs/concepts/limits/overview

**Comment by hyoban** [comment]
Maybe it would be better to make it a local app
