### ISSUE TITLE
Memos to JSON

### ISSUE THREAD

**Issue by jxpsert** [hyoban/kirika#2]
Hi there! I would appreciate a way to export Memos to JSON, as to keep the time and ID of each memo.

For example, something like
```json
{
    "memos": [
        {   
            "id": 81,
            "created": "2011-10-10T14:48:00",
            "content": "**note header**\nthis is the content of the memo"
        },
        {   
            "id": 82,
            "created": "2011-10-10T14:50:00",
            "content": "**note header**\nthis is the content of the memo"
        }
    ]
}
```

The 'local' export option is fine, but I would love to keep the datetimes.

**Comment by hyoban** [comment]
What about saving time in frontmatter? If you want JSON format, just visit OpenAPI directly.

**Comment by hyoban** [comment]
It should be okay, make sure you select the WithFrontMatter option
<img width="666" alt="image" src="https://github.com/hyoban/kirika/assets/38493346/46822ce0-e584-4fac-9d66-ab525dd157f1">
