### ISSUE TITLE
Google Keep notes -> memos

### ISSUE THREAD

**Issue by hyoban** [hyoban/kirika#3]
https://github.com/orgs/usememos/discussions/1705

**Comment by hyoban** [comment]
@jon-f-novastor

Try importing your Google keep notes here. 
https://kirika.up.railway.app/google-keep-to-memos

Let me know if you run into any issues and I'll fix them ASAP

**Comment by jon-f-novabackup** [comment]
@hyoban I tried to utilize the Google Keep to Memos import function on https://kirika.up.railway.app/ and a few minutes after clicking the start button to process the import on that website, it returned to be able to click on the button. My Memos instance that I was importing to did not show any difference after refreshing the Memos web page. I think I tried that same import function a couple more times earlier today (about 4 hours ago now), but then I noticed about 30 minutes later that the entire website is no longer responding. I verified it is not my connection to the internet. I tried it from another machine on a different internet connection and it was showing this same error on the website overall. The error is seen here:

![image](https://github.com/hyoban/kirika/assets/50121594/101961a7-2387-437f-8f7e-7e2447ddfba1)

I think possibly the website went down at that point a few hours ago. I was going to utilize the Markdown to Memos import feature of the website and since the website is down I can't attempt that test at the moment.

**Comment by jon-f-novabackup** [comment]
> 

It looks like the website went back up on 05/30/23 at around 10:57 PM PDT for me to attempt the "Local (Markdown) > Memos" import at least, now that I have converted the Google Keep notes to Markdown (using https://github.com/erikelisath/keep-to-markdown).

**Comment by hyoban** [comment]
I restarted it, can you try it again now?

**Comment by jon-f-novabackup** [comment]
> I restarted it, can you try it again now?

Looks good now thanks!

**Comment by jon-f-novabackup** [comment]
@hyoban unfortunately the website crashed again two mins ago at 11:33 PM PDT, and shows just a "stream timeout" message again, after trying the different Local (Markdown) to Memos function, for I believe the second time in a row as it did not import anything into Memos the first time I tried it at around 11:20 PM PDT today (which is a totally different function as to what caused this before a few hours ago, where I was only utilizing the brand new Google Keep to Memos function there to test that new function): 

![image](https://github.com/hyoban/kirika/assets/50121594/1e66f7cd-6a03-4caf-9ea6-c907a87ee774)

The error came after about 6-7 minutes of the website working to import my 289 MB markdown .zip file (keep-to-markdown_notes_05302023.zip), which is about how much time it took originally to cause that same stream timeout message to crash the entire website on my 583 MB Google Keep .zip file (takeout-20230530T194146Z-001.zip). I will stop utilizing the website functions for now (until I hear back), as I don't want it to take down the website again today, it could be something in my .zip files for what it is trying to process as to cause the web app to crash.

Note: I'm using Memos 0.13.1 (latest release) and my admin user's currently working Settings > OpenAPI string (in the same Google Chrome and Firefox web browsers that Memos is working already in to login with using OAuth). For my 289 MB markdown .zip file (keep-to-markdown_notes_05302023.zip), there are two folders in the .zip, notes and resources, the notes folder contains 278 .md (markdown) files, and the resources folder contains 163 .jpg files. The existing Memos instance only has 5 total notes (and 6 x image assets) stored, and one archived note, for the Memos admin user that is utilized by the OpenAPI string (that I'm specifying to import using Kirika with), prior to attempting any data imports with any method.

**Comment by hyoban** [comment]
Looks like it fails the test for uploading relatively large files.

I haven't used google keep for a long time. If you have a relatively large export file, welcome to send it to my mail so that I can test it

**Comment by hyoban** [comment]
After thinking about it a bit, I think a desktop app would be more suitable, I'll try to get it out by the end of the week

**Comment by jon-f-novabackup** [comment]
Sounds good, I just sent you that in case you get a chance to try importing it with the desktop app. It is not all that large at 583 MB as I commented on two days ago. I will try out your desktop app once you can email me a dl link for it, if you can't first test it with my takeout*.zip file as well!

**Comment by hyoban** [comment]
@jon-f-novastor Thanks a lot, I'll do my best to get it imported into memos, this will be a necessary goal before I release a desktop version

**Comment by jon-f-novabackup** [comment]
I just wanted to report back that the desktop version ultimately did work to convert the same 583 MB Google Keep .zip file (takeout-20230530T194146Z-001.zip) that I had reported that not able to import using the Kirika web version https://kirika.up.railway.app/google-keep-to-memos. The imported contents looked good, and retained the screenshots that existed in the Google Keep entries, it also retained the few native created entries that had already existed in Memos. Thanks @hyoban!

**Comment by hyoban** [comment]
glad to hear this
